### ISSUE TITLE
Migrate to ES6

### ISSUE THREAD

**Issue by beeman** [beeman/loopback-angular-admin#179]
I have started working on migrating this project to ES6. I'm working on this in the [develop branch](https://github.com/beeman/loopback-angular-admin/tree/develop).

The version in this branch will be the first 1.0.0 release. 
### Todo
- [x] Install babel to enable usage of ES6 on the back-end
- [x] Install and configure ESLint rules based on [standardjs](standardjs.com) (with some additions)
- [x] Replace Grunt with Gulp as a task-runner
- [x] Leverage webpack + babel to enable usage of ES6 in the front-end 
- [x] Remove bower in favor of npm packages for the front end
- [ ] Restructure directory layout (move app code into a `src` dir) 
- [ ] Implement [bootstrap-admin-ui](https://github.com/beeman/bootstrap-admin-ui) (fork of rdash-ui)
- [ ] Add a build-step
- [ ] Add tests for back- and frond end
### Known issues
- [ ] The dropdowns in the navbar don't work
- [ ] The back end and front end servers are started separately (`npm run dev` and `webpack-dev-server`)

If you find any more issues, please let me know.

**Comment by PhilippeCorreges** [comment]
Hi!!
Thanks for your help and sorry for the late reply.
Some issues still here : 
I upgraded node to 6.2.0 and strongloop to 2.28.0 (Latest stable) => deprecated warnings in package.json : 
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.5 should be installed with -g

**Comment by beeman** [comment]
Closing in favor of work on project based on Angular 2+ / TypeScript. Follow here https://github.com/beeman/loopback-angular-admin/issues/202
